/* =========================================================
   STM32 Temperature & Humidity Monitor using DHT11 + LCD
   Author: Vandana
   ========================================================= */

#include "main.h"
#include <stdio.h>
#include <string.h>

/* ----------- DHT11 Pin Configuration ----------- */
#define DHT11_PORT GPIOA
#define DHT11_PIN  GPIO_PIN_1

/* ----------- Function Declarations ----------- */
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
void DHT11_Start(void);
uint8_t DHT11_Read(void);
void delay_us(uint16_t us);

/* ----------- Global Variables ----------- */
uint8_t Rh_byte1, Rh_byte2, Temp_byte1, Temp_byte2;
uint16_t SUM;

/* Microsecond delay using timer */
extern TIM_HandleTypeDef htim1;

/* ========================================================= */

void DHT11_Start(void)
{
    GPIO_InitTypeDef GPIO_InitStruct = {0};

    /* Set pin as output */
    GPIO_InitStruct.Pin = DHT11_PIN;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
    HAL_GPIO_Init(DHT11_PORT, &GPIO_InitStruct);

    HAL_GPIO_WritePin(DHT11_PORT, DHT11_PIN, 0);
    HAL_Delay(18);

    HAL_GPIO_WritePin(DHT11_PORT, DHT11_PIN, 1);
    delay_us(30);

    /* Set pin as input */
    GPIO_InitStruct.Mode = GPIO_MODE_INPUT;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    HAL_GPIO_Init(DHT11_PORT, &GPIO_InitStruct);
}

uint8_t DHT11_Read(void)
{
    uint8_t i, j;

    for (j = 0; j < 8; j++)
    {
        while (!(HAL_GPIO_ReadPin(DHT11_PORT, DHT11_PIN)));
        delay_us(40);

        if (!(HAL_GPIO_ReadPin(DHT11_PORT, DHT11_PIN)))
            i &= ~(1 << (7 - j));
        else
            i |= (1 << (7 - j));

        while (HAL_GPIO_ReadPin(DHT11_PORT, DHT11_PIN));
    }
    return i;
}

/* Microsecond delay */
void delay_us(uint16_t us)
{
    __HAL_TIM_SET_COUNTER(&htim1, 0);
    while (__HAL_TIM_GET_COUNTER(&htim1) < us);
}

/* ========================================================= */

int main(void)
{
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();

    HAL_TIM_Base_Start(&htim1);

    while (1)
    {
        DHT11_Start();

        Rh_byte1 = DHT11_Read();
        Rh_byte2 = DHT11_Read();
        Temp_byte1 = DHT11_Read();
        Temp_byte2 = DHT11_Read();
        SUM = DHT11_Read();

        char buffer[50];

        if (SUM == (Rh_byte1 + Rh_byte2 + Temp_byte1 + Temp_byte2))
        {
            sprintf(buffer, "Temp: %d C  Hum: %d %%\r\n",
                    Temp_byte1, Rh_byte1);
        }
        else
        {
            sprintf(buffer, "Sensor Error!\r\n");
        }

        HAL_Delay(2000);
    }
}

/* ========================================================= */
/* GPIO Initialization */

static void MX_GPIO_Init(void)
{
    __HAL_RCC_GPIOA_CLK_ENABLE();
}

/* System Clock (Basic config) */
void SystemClock_Config(void)
{
    /* Default clock config generated by CubeMX */
}
